// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for blog_posts documents
 */
interface BlogPostsDocumentData {
  /**
   * Title field in *blog_posts*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: blog title
   * - **API ID Path**: blog_posts.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Excerpt field in *blog_posts*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Brief description for blog cards..."
   * - **API ID Path**: blog_posts.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  excerpt: prismic.RichTextField;

  /**
   * featured image field in *blog_posts*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_posts.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Content field in *blog_posts*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: blog content...
   * - **API ID Path**: blog_posts.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField /**
   * Author field in *blog_posts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Allan
   * - **API ID Path**: blog_posts.author
   * - **Tab**: Author
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  author: prismic.KeyTextField /**
   * Published Date field in *blog_posts*
   *
   * - **Field Type**: Date
   * - **Placeholder**: day of publish
   * - **API ID Path**: blog_posts.published_date
   * - **Tab**: Published Date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */;
  published_date: prismic.DateField /**
   * Category field in *blog_posts*
   *
   * - **Field Type**: Select
   * - **Placeholder**: categories
   * - **API ID Path**: blog_posts.category
   * - **Tab**: Category
   * - **Documentation**: https://prismic.io/docs/fields/select
   */;
  category: prismic.SelectField<"Security" | "Tutorials" | "Best Practices"> /**
   * Featured Post field in *blog_posts*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: blog_posts.featured_post
   * - **Tab**: Featured Post
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */;
  featured_post: prismic.BooleanField /**
   * Meta Title field in *blog_posts*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_posts.meta_title
   * - **Tab**: Meta Title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */;
  meta_title: prismic.RichTextField /**
   * Meta Description field in *blog_posts*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_posts.meta_description
   * - **Tab**: Meta Description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */;
  meta_description: prismic.RichTextField;
}

/**
 * blog_posts document from Prismic
 *
 * - **API ID**: `blog_posts`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostsDocumentData>,
    "blog_posts",
    Lang
  >;

type PacgieBlogDocumentDataSlicesSlice = never;

/**
 * Content for pacgie_blog documents
 */
interface PacgieBlogDocumentData {
  /**
   * Page Title field in *pacgie_blog*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: latest gudies
   * - **API ID Path**: pacgie_blog.page_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  page_title: prismic.RichTextField;

  /**
   * Hero Section field in *pacgie_blog*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Write an engaging introduction about your security guides...
   * - **API ID Path**: pacgie_blog.hero_section
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_section: prismic.RichTextField;

  /**
   * Slice Zone field in *pacgie_blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: pacgie_blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PacgieBlogDocumentDataSlicesSlice> /**
   * Meta Title field in *pacgie_blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Dependency Security Guides for Developers
   * - **API ID Path**: pacgie_blog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *pacgie_blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Expert guides on dependency security, vulnerability management, and secure coding practices...
   * - **API ID Path**: pacgie_blog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *pacgie_blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pacgie_blog.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * pacgie_blog document from Prismic
 *
 * - **API ID**: `pacgie_blog`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PacgieBlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PacgieBlogDocumentData>,
    "pacgie_blog",
    Lang
  >;

export type AllDocumentTypes = BlogPostsDocument | PacgieBlogDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogPostsDocument,
      BlogPostsDocumentData,
      PacgieBlogDocument,
      PacgieBlogDocumentData,
      PacgieBlogDocumentDataSlicesSlice,
      AllDocumentTypes,
    };
  }
}
